server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb+srv://${user.name}:${user.pwd}@cluster0.gs6m7al.mongodb.net/${user.dbName}?retryWrites=true&w=majority